### ISSUE TITLE
A bit more features

### ISSUE THREAD

**Issue by stereobooster** [shime/node-vs-ruby-io#4]
- Would be nice to compare memory and CPU
- Would be nice to make sure all tests use same resampling algorithm. I suppose they are using lancos3, but just need to make sure
- Would be nice to show statistical error regions in graph, maybe something like candel graph

**Comment by hmistry** [comment]
- See PR #8 for memory usage - not sure if its the right way especially with the external libraries being called. 
- All tests are using the same resampling algorithm (lancos3).
- Statistical error between runs is very roughly <~10 ms so I didn't bother with that.

**Comment by stereobooster** [comment]
@hmistry nice. I will close this, progress can be tracked in PR
